#!/bin/sh

checksum()
{
    BS=4194304 # 4Mb
    dd bs=${BS} count=1 if="$1" | sha256sum | awk '{ print $1 }'
}

case "$1" in
    slot-post-install)
        env > /tmp/log
        if [ "${RAUC_SLOT_NAME}" = "rootfs.1" ] || [ "${RAUC_SLOT_NAME}" = "rootfs.0" ]; then
            export RAUC_IMAGE_NAME="rootfs.squashfs"
        elif [ "${RAUC_SLOT_NAME}" = "boot.1" ] || [ "${RAUC_SLOT_NAME}" = "boot.0" ]; then
            export RAUC_IMAGE_NAME="Image.img"
        elif [ "${RAUC_SLOT_NAME}" = "fdt.0" ] || [ "${RAUC_SLOT_NAME}" = "fdt.1" ]; then
            export RAUC_IMAGE_NAME="${fdt_img}"
        fi
        export RAUC_IMAGE_NAME="${RAUC_BUNDLE_MOUNT_POINT}/${RAUC_IMAGE_NAME}"
        export SIZE=""
        SIZE=$(wc -c < "${RAUC_IMAGE_NAME}")
        export RAUC_IMAGE_DIGEST=""
        RAUC_IMAGE_DIGEST=$(checksum "${RAUC_IMAGE_NAME}")
        sync && echo 3 > /proc/sys/vm/drop_caches
        RAUC_SLOT_DIGEST=$(checksum "${RAUC_SLOT_DEVICE}")
        if [ "${RAUC_SLOT_DIGEST}" != "${RAUC_IMAGE_DIGEST}" ]; then
            {
                echo "${RAUC_SLOT_DEVICE}"
                echo "${SIZE}"
                echo "${RAUC_IMAGE_NAME}"
                echo "${RAUC_SLOT_DIGEST}"
                echo "${RAUC_IMAGE_DIGEST} -"
            } >> /tmp/log
            exit 100
        fi
        ;;
    *)
        exit 99
        ;;
esac
exit 0
